[project]
name = "FauxPID"
version = "0.1.0"
description = "A small app for generating and analyzing DICOM images."
readme = "README.md"
requires-python = ">=3.12"
authors = [
    { name = "June Yu" },
]
dependencies = [
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "pydicom>=2.4.5",
    "pylinac>=3.44.0",
]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]

# Add this block to tell uv how to build your package editably
[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["FauxPID"]